services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development
    command: npm run dev:client

  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development
    command: npm run dev:server