FROM node:22-alpine

WORKDIR /app

COPY package.json package-lock.json ./
COPY packages/client/package.json ./packages/client/package.json

RUN npm install --workspace=client

COPY packages/client ./packages/client
COPY packages/shared ./packages/shared

RUN npm run build:client

EXPOSE 80

CMD ["npm", "run", "start:client"]
